  Vagrant.configure("2") do |config|
  config.vm.box = "Obovtunov/CentosLAMP"
  config.vm.box_version = "1.1"
  config.ssh.insert_key = false  
  config.vm.synced_folder ".", "/vagrant"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"
 
 config.vm.provision "shell", inline: <<-SHELL
    sudo chmod 775 /var/www
    sudo mkdir -p /var/www/01-demosite-static	
    sudo mkdir -p /var/www/01-demosite-php
    sudo cp -f /vagrant/httpd.conf /etc/httpd/conf/
    sudo cp -f /vagrant/000-default.conf /etc/httpd/conf.d/  
    sudo cp /vagrant/index.html /var/www/01-demosite-static/ 
    sudo cp /vagrant/index.php /var/www/01-demosite-php/
    sudo systemctl restart httpd
     SHELL
end
