---
- name: Install soft master
  hosts: master
  become: yes
  tasks: 
    - name: Install Server Puppet
      shell: yum install -y puppetserver git 

    - name: Install Q10k
      shell: /opt/puppetlabs/puppet/bin/gem install r10k 

    - name: Create file $ directory
      file:
        path: /etc/puppetlabs/r10k
        state: directory
    - name: Copy Files R10K
      copy: 
        src: /vagrant/r10k.yaml
        dest: /etc/puppetlabs/r10k/
    - name: Connect to reposit
      become: yes
      shell: sudo /opt/puppetlabs/puppet/bin/r10k deploy environment -p
    
    - name: Change Ram
      become: yes
      replace:
        path: /etc/sysconfig/puppetserver
        regexp: 'JAVA_ARGS="-Xms2g -Xmx2g'
        replace: 'JAVA_ARGS="-Xms256m -Xmx256m'

    - name: ADD hosts
      lineinfile:
        path: /etc/hosts
        line: "{{item}}"
      with_items:
        - '192.168.33.10 master.puppet'
        - '192.168.33.11 slave2.puppet'
        - '192.168.33.12 slave1.puppet'

    - name: ADD host puppetserver
      lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        line: "{{item}}"
      with_items:
         - server = master.puppet
         - autosign = true 
              
    - name: Enable Puppet
      systemd:
        name: puppetserver
        enabled: yes
        state: started

    - name: Start Puppet
      systemd:
        state: started
        name: puppetserver

    - name: Disable SSH press key
      replace:
        path: /etc/ansible/ansible.cfg
        regexp: '# some basic default values...'
        replace: 'host_key_checking=false'

    - name: Start playbook Slave
      become: yes
      shell: sudo ansible-playbook -i /vagrant/hosts /vagrant/slave.yaml
