Vagrant.configure("2") do |config|
   config.vm.box = "centos/8"
   
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus   = 1     
   end
     config.vm.provision "shell", inline: <<-shell
       sudo yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
       sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
       sudo systemctl restart sshd.service
       shell

   
     config.vm.define "slave1.puppet" do |slave|
      slave.vm.network "private_network", ip: "192.168.33.12"
      slave.vm.network "forwarded_port", guest: 80, host: 8080
      slave.vm.hostname = "slave1.puppet"   
    end

     config.vm.define "slave2.puppet" do |slave|
       slave.vm.network "private_network", ip: "192.168.33.11"
       slave.vm.network "forwarded_port", guest: 81, host: 8081      
       slave.vm.hostname = "slave2.puppet"
     end   

       config.vm.define "master.puppet" do |master|
       master.vm.network "private_network", ip: "192.168.33.10"
       master.vm.hostname = "master.puppet"
       
       master.vm.provision "ansible_local" do |ansible|
       ansible.playbook = "task-04.yaml"
       ansible.become = true
       ansible.inventory_path = "./hosts"       
        end
      end
end 
