Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.synced_folder ".", "/vagrant"

       config.vm.define "docker" do |master|
         master.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
         master.vm.hostname = "docker"
         master.vm.provider "virtualbox" do |vb|
         vb.memory = 1024
         vb.cpus   = 1     
          end


       master.vm.provision "shell", inline: <<-shell
         sudo apt-get update
         sudo apt install -y docker.io
       shell
      end
end 
