---
- name: Install jenkins 
  hosts: master
  become: yes
  tasks:
    - name: Install start soft
      package:
         name:
           - curl
           - git
           - build-essential
           - default-jre
         state: present

    - name: Add Jenkins apt repository key.
      apt_key:
        url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
        state: present

    - name: ADD KEY 
      shell: |
          sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
          /etc/apt/sources.list.d/jenkins.list'
          apt-get update
          

    - name: Install Jenkins
      package:
         name:
          jenkins
         state: present

    - name: Make Directory
      file:
        path: /var/lib/jenkins/init.groovy.d/basic-security.groovy
        state: directory

    - name: Copying Groovy Script For Deafult Jenkins User Creation
      copy:
        src: /vagrant/jenkins_script.groovy
        dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
        

    - name: Restarting Jenkins
      service:
        name: jenkins
        state: restarted
      
#    - name: "Wait For Jenkins To Come Up"
#      uri:
#        url: "http://192.168.33.10/cli/"
#        status_code: 403
#      register: result
#      until: result.status == 403
#      retries: 6
#      delay: 15


    - name: Wait for Jenkins to start up before proceeding.
      command: >
        curl -D - --silent --max-time 5 http://192.168.33.10:8080/cli/
      args:
        warn: false
      register: result
      until: >
        (result.stdout.find("403 Forbidden") != -1)
        or (result.stdout.find("200 OK") != -1)
        and (result.stdout.find("Please wait while") == -1)
      retries: 6
      delay: 15
      changed_when: false
      check_mode: false
     

    - name: Removing Groovy Script
      file:
        path: /var/lib/jenkins/init.groovy.d/basic-security.groovy
        state: absent

    - name: Restarting Jenkins
      service:
        name: jenkins
        state: restarted
      

 #   - name: "Wait For Jenkins To Come Up"
 #     uri:
 #       url: "http://192.168.33.10/cli/"
 #       status_code: 403
 #     register: result
 #     until: result.status == 403
 #     retries: 6
 #     delay: 15
       