version: '3'
services:
  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile
    ports:
      - 80:8080
    networks:
      - work
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - exchange:/var/lib/jenkins/workspace 
  nexus:
    build:
      context: ./nexus
      dockerfile: Dockerfile
    ports:
      - 81:8081
    networks:
      - work
    container_name: nexus
networks:
  work: 
volumes: 
  exchange: