---
- name: Disable selinux
  hosts: all
  become: yes
  tasks: 
    - name: Firewall disabled
      selinux:
        policy: targeted
        state: permissive
        
    - name: Install Pupet RPM
      shell: yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm

- name: Install soft master
  hosts: master
  become: yes
  tasks: 
    - name: Install Server Puppet
      package:
        name: 
          - puppetserver
          - git
        state: present

    - name: Install Q10k
      command: /opt/puppetlabs/puppet/bin/gem install r10k 

    - name: Create file $ directory
      file:
        path: /etc/puppetlabs/r10k
        state: directory

    - name: Copy Files R10K
      copy: 
        src: /vagrant/r10k.yaml
        dest: /etc/puppetlabs/r10k/

    - name: Connect to reposit
      command: /opt/puppetlabs/puppet/bin/r10k deploy environment -p
    
    - name: Change Ram
      replace:
        path: /etc/sysconfig/puppetserver
        regexp: 'JAVA_ARGS="-Xms2g -Xmx2g'
        replace: 'JAVA_ARGS="-Xms256m -Xmx256m'

    - name: ADD hosts
      lineinfile:
        path: /etc/hosts
        line: "{{item}}"
      with_items:
         - '192.168.33.10 master.puppet'
         - '192.168.33.11 slave2.puppet'
         - '192.168.33.12 slave1.puppet'
         - '192.168.33.20 mineserver.puppet'

    - name: ADD host puppetserver
      lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        line: "{{item}}"
      with_items:
         - 'autosign = true' 
         - ''
         - '[agent]'
         - 'server = master.puppet'
         - 'runinterval = 2m'
              
    - name: Enable Puppet
      systemd:
        name: puppetserver
        enabled: yes
        state: started
 
    - name: Enable Puppet Agent
      systemd:
        name: puppet
        enabled: yes
        state: started

             
- name: Install soft slave 
  hosts: slave, game
  become: yes
  tasks: 

    - name: Install Puppet agent
      package:
         name: puppet-agent
         state: present

    - name: ADD hosts
      lineinfile:
        path: /etc/hosts
        line: '192.168.33.10 master.puppet puppet'
   
    - name: Make connect to puppet-server
      lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        line: "{{item}}"
      with_items:
         - '[agent]'
         - 'server = master.puppet' 
         - 'runinterval = 2m'

    - name: Enable Puppet
      systemd:
        name: puppet
        enabled: yes
        state: started

    