Vagrant.configure("2") do |config|
   config.vm.box = "centos/8"
   
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus   = 2     
   end
     config.vm.define "slave1.puppet" do |slave|
      slave.vm.network "private_network", ip: "192.168.33.12"
      slave.vm.network "forwarded_port", guest: 80, host: 8080
      slave.vm.hostname = "slave1.puppet"   
    end

     config.vm.define "slave2.puppet" do |slave|
       slave.vm.network "private_network", ip: "192.168.33.11"
       slave.vm.network "forwarded_port", guest: 81, host: 8081      
       slave.vm.hostname = "slave2.puppet"
     end   
  
       config.vm.define "mineserver.puppet" do |game|
       game.vm.network "private_network", ip: "192.168.33.20"
       game.vm.hostname = "mineserver.puppet"
      end 


       config.vm.define "master.puppet" do |master|
       master.vm.network "private_network", ip: "192.168.33.10"
       master.vm.network "forwarded_port", guest: 88, host: 8088      
       master.vm.hostname = "master.puppet"
         
       master.vm.provision :file, source: '.vagrant/machines/slave1.puppet/virtualbox/private_key', destination: '/home/vagrant/private_key_slave1'
       master.vm.provision :file, source: '.vagrant/machines/slave2.puppet/virtualbox/private_key', destination: '/home/vagrant/private_key_slave2'
       master.vm.provision :file, source: '.vagrant/machines/mineserver.puppet/virtualbox/private_key', destination: '/home/vagrant/private_key_mineserver'

       master.vm.provision "shell", inline: <<-shell
         sudo chmod =600 /home/vagrant/private_key_slave1
         sudo chmod =600 /home/vagrant/private_key_slave2
         sudo chmod =600 /home/vagrant/private_key_mineserver
       shell
     
     
       master.vm.provision "ansible_local" do |ansible|
       ansible.playbook = "task-05.yaml"
       ansible.limit = "all"
       ansible.become = true
       ansible.inventory_path = "./hosts"       
        end
      end
end 
