apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-ip-deployment
spec:
  selector:
    matchLabels:
      app: static-ip
  replicas: 3
  template:
    metadata:
      labels:
        app: static-ip
    spec:
      containers:
      - name: task-10
        image: flashboy/test
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 1
          httpGet:
            path: /
            port: 80
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 1
          httpGet:
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: task-10-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: static-ip
