---
- name: Server_listen_80_81
  hosts: all
  become: yes

  tasks: 
    
    - name: Install LXC
      package:
        name:
          - lxc
          - lxc-templates
          - python-pip
          - lxc-dev
        state: present

    - name: Install LXC2
      pip:
        name: lxc-python2       
    
    - name: Create file $ directory
      file:
        path: /etc/default/lxc-net
        state: touch
    - file:    
        path: /etc/lxc/lxc-usernet
        state: touch
    - file:
        path: /var/lib/lxc/cent1/rootfs/var/www/01-demosite-static
        state: directory
    - file:
        path: /var/lib/lxc/cent2/rootfs/var/www/01-demosite-php
        state: directory


    - name: Make LAN 1
      lineinfile:
        path: /etc/default/lxc-net
        line: "{{item}}"
      with_items:
         - USE_LXC_BRIDGE="true"
         - LXC_BRIDGE="lxcbr0" 
         - LXC_ADDR="10.0.3.1"
         - LXC_NETMASK="255.255.255.0"
         - LXC_NETWORK="10.0.3.0/24"
         - LXC_DHCP_RANGE="10.0.3.2,10.0.3.254"
         - LXC_DHCP_MAX="253"
         - LXC_DHCP_CONFILE=""
         - LXC_DOMAIN=""
    
    - name: Make LAN 2
      lineinfile:
        path: /etc/lxc/default.conf
        line: "{{item}}"
      with_items:
         - lxc.net.0.flags = up
         - lxc.net.0.link = lxcbr0 
         - lxc.start.auto = 1

    - name: Make LAN 3
      lineinfile:
        path: /etc/lxc/lxc-usernet 
        line: "root veth lxcbr0 10"
  
    - name: Change 
      replace:
        path: /etc/default/lxc
        regexp: 'USE_LXC_BRIDGE="false"'
        replace: 'USE_LXC_BRIDGE="true"'
    - replace:
        path: /etc/lxc/default.conf
        regexp: 'lxc.net.0.type = empty'
        replace: 'lxc.net.0.type = veth'
    - replace:
        path: /etc/lxc/default.conf
        regexp: 'lxc.apparmor.profile = generated'
        replace: 'lxc.apparmor.profile = unconfined'
    
    - name: Enabled_LAN 
      systemd:
        name: lxc-net
        state: started
  
    - name: Create conteiner 1
      lxc_container:
        name: cent1
        template: download
        template_options: --dist centos --release 8 --arch amd64
        state: started
        container_command: |
          sleep 10
          yum -y install httpd
          yum -y install php
          systemctl enable httpd
          systemctl start httpd
          sleep 2   

    
    - name: Create conteiner 2
      lxc_container:
        name: cent2
        template: download
        template_options: --dist centos --release 8 --arch amd64
        state: started
        container_command: |
          sleep 10
          yum -y install httpd
          yum -y install php
          systemctl enable httpd
          systemctl start httpd   
          sleep 2  

    - name: Copy Files HTML
      copy: 
        src: /vagrant/index.html
        dest: /var/lib/lxc/cent1/rootfs/var/www/01-demosite-static/
    - copy:
        src: /vagrant/index.php
        dest: /var/lib/lxc/cent2/rootfs/var/www/01-demosite-php/

    - name: Add port 81 conteiner 2
      replace:
        path: /var/lib/lxc/cent2/rootfs/etc/httpd/conf/httpd.conf
        regexp: 'Listen 80'
        replace: 'Listen 81'

    - name: VirtualHost conteiner 2
      file:
        path: /var/lib/lxc/cent2/rootfs/etc/httpd/conf.d/default.conf
        state: touch
    - lineinfile:
        path: /var/lib/lxc/cent2/rootfs/etc/httpd/conf.d/default.conf
        line: "{{item}}"
      with_items:
         - <VirtualHost *:81>
         - DocumentRoot /var/www/01-demosite-php/ 
         - </VirtualHost>

    - name: VirtualHost conteiner 1
      file:
        path: /var/lib/lxc/cent1/rootfs/etc/httpd/conf.d/default.conf
        state: touch
    - lineinfile:
        path: /var/lib/lxc/cent1/rootfs/etc/httpd/conf.d/default.conf
        line: "{{item}}"
      with_items:
         - <VirtualHost *:80>
         - DocumentRoot /var/www/01-demosite-static/ 
         - </VirtualHost>


    - name: Restart Apacher cent1
      lxc_container:
        name: cent1
        container_command: |
          systemctl restart httpd

    - name: Restart Apacher cent2
      lxc_container:
        name: cent2
        container_command: |
          systemctl restart httpd

    - name: IPTABLES
      shell: ip=$(sudo lxc-info -n cent1 -iH);sudo iptables -t nat -I PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination ${ip}:80
    - shell: ip=$(sudo lxc-info -n cent2 -iH);sudo iptables -t nat -I PREROUTING -i eth0 -p tcp --dport 81 -j DNAT --to-destination ${ip}:81
  