version: '3'
services:
  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile
    ports:
      - 80:8080
    networks:
      - Jenkins
    container_name: jenkins
networks:
  Jenkins: 
