Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

       config.vm.define "docker" do |master|
           master.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
           master.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"
           master.vm.hostname = "docker.vm"
             master.vm.provider "virtualbox" do |vb|
               vb.memory = 2048
               vb.cpus   = 2
             end
             master.vm.provision "shell", inline: <<-shell
               sudo apt-get update
               sudo apt install -y docker.io docker-compose
               sudo usermod -a -G docker vagrant
             shell
       end
end 
